// <auto-generated />
using System;
using Licitacija.Services.ZavrsneRadnjeAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Licitacija.Services.ZavrsneRadnjeAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230214200242_createInitials")]
    partial class createInitials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Licitacija.Services.ZavrsneRadnjeAPI.Entities.ZavrsneRadnje", b =>
                {
                    b.Property<Guid>("ZavrsnaRadnjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FazaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZavrsnaRadnjaNaziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZavrsnaRadnjaId");

                    b.ToTable("Prioritet");
                });
#pragma warning restore 612, 618
        }
    }
}
